### ISSUE TITLE
支払い情報のCRUD（一覧、追加）

### ISSUE THREAD

**Issue by mami-inuzuka** [mami-inuzuka/seppanda#49]
# TODO
- [x] CRUDについて復習
    - [x] 独習Ruby on Rails
- [x] モデルの作成
    - [x] Paymentモデルの作成
    - [x] 関連付けの設定
    - [x] バリデーションを設定
        - [x] amount
            - [x] 必須項目
            - [x] 半角数字のみ
            - [x] 整数のみ
            - [x] 0はNG
            - [x] 最大金額
            - [x] 最小金額
    - [x] テストの作成
        - [x] Paymentモデルスペック
        - [x] Payment API リクエストスペック
- [x] 一覧
    - [x] Controllerの作成(payments#index)
    - [x] Homeコンポーネントで表示
        - [x] `lib/api/getPayments.ts`を作成（axiosでGETリクエストを送る）
        - [x] `Home.tsx`に`handleGetPayments`関数を作成する
            - [x] `try...catch`で`getPayments`関数を実行する
        - [x] 日付のフォーマットを整える
        - [x] 取得paymentsデータ内にユーザーオブジェクトを入れ込む
        - [x] 新しく追加した際に画面が更新されるようにする
        - [x] 一番上が新しいデータとなるようにする
- [x] 登録
    - [x] Controllerの作成(payments#create)
    - [x] フロントから登録できるようにする
    - [x] 登録したらキーパッドの値を0にする

→長くなったので削除と更新は別PRで実装
